// Generated by https://quicktype.io

export interface SrAPIResponse {
    copyright:  string;
    shows:      Show[];
    pagination: Pagination;
  }
  
  export interface Pagination {
    page:       number;
    size:       number;
    totalhits:  number;
    totalpages: number;
    nextpage:   string;
  }
  
  export interface Show {
    id:               number;
    title:            string;
    description:      string;
    dateutc:          string;
    starttimeutc:     string;
    endtimeutc?:      string;
    type:             Type;
    imageurl:         string;
    imageurltemplate: string;
    listenpodfile?:   Podfile;
    downloadpodfile?: Podfile;
    program:          Program;
    broadcast?:       Broadcast;
  }
  
  export interface Broadcast {
    playlist:          Playlist;
    broadcastfiles:    Playlist[];
    availablestoputc?: string;
  }
  
  export interface Playlist {
    duration:       number;
    publishdateutc: string;
    id:             number;
    url:            string;
    statkey:        string;
  }
  
  export interface Podfile {
    title:            string;
    description:      string;
    filesizeinbytes:  number;
    program:          Program;
    availablefromutc: string;
    duration:         number;
    publishdateutc:   string;
    id:               number;
    url:              string;
    statkey:          string;
  }
  
  export interface Program {
    id:   number;
    name: string;
  }
  
  export enum Type {
    Broadcast = "broadcast",
    Pod = "pod",
  }